GET http://localhost:3001/api/persons/5a7708053ce1900d741b2c7c

###

GET http://localhost:3001/api/persons

### 
PUT http://localhost:3001/api/persons/5a77259f8ebec710645432e9

###

GET http://localhost:3001/info
